### ISSUE TITLE
Weird black bar on screen - maybe something with ClassTimers

### ISSUE THREAD

**Issue by HolySephi** [liquidbase/DuffedUIv9#28] opened 2020-10-23 20:44 UTC
Hello,

since two or three updates there is a strange black bar onscreen - if i disable and reenable ClassTimers the bar hides for some time but emerges again. Here are two screenshots - second is framestack - i guess it's "TimerTrackerTimer1StatusBar" but it never has any content:
![WoWScrnShot_102320_223946](https://user-images.githubusercontent.com/1346621/97052346-1a3b7200-1581-11eb-956d-22c6973107ff.jpg)
![WoWScrnShot_102320_223957](https://user-images.githubusercontent.com/1346621/97052348-1c9dcc00-1581-11eb-9da1-dd11d678e060.jpg)

and i dont have any runes on my dk - do i miss something in the config or are there no runes?

**Comment by liquidbase** [comment] 2020-10-24 06:39
I look at myself today. Runes should actually be displayed as there are no problems here. The timer bar in the middle is actually intended for something like the breath display and shouldn't be seen that way.

**Comment by liquidbase** [comment] 2020-10-24 06:46
Another question about the runes, do you use the option "Connect the classbar to the unitframe"?

**Comment by liquidbase** [comment] 2020-10-24 07:51
Issue with runes is fixed with https://github.com/liquidbase/DuffedUIv9/commit/9370f41b698ac79ac3a766cff9645dc7b042228d

Issue with TimerTracker can not resolved at the current moment.
Do you possibly use another add-on here that accesses the frame? I have now tested several situations and do not get any display of the background myself.

**Comment by HolySephi** [comment] 2020-10-24 08:35
Ah yes, "Connect the classbar to the unitframe" make the classbar completely disappear - disabling the setting shows the classbar with runes perfectly fine in the middle of the screen.

And for the addons - maybe an addon interferes here - i dont have many:
![image](https://user-images.githubusercontent.com/1346621/97077506-8ef3c800-15e4-11eb-8b16-28a29adf5eca.png)

Maybe one of the raid addons - its a bit tricky to track down because every time i disable an addon the bar vanishes for some time - and it doesnt matter which addon i disable.

**Comment by liquidbase** [comment] 2020-10-24 10:35
Both options should now work as intended.

I also suspect the raid addons here. One possibility would be to deactivate them all and then activate them one after the other to see which one has the problem.

btw which tool is that there on the screenshot? Looks good :)

**Comment by HolySephi** [comment] 2020-10-24 10:40
As i'm unable to reproduce the bar reliable testing which addon might cause this problem is nearly impossible :-(

Do you mean the addon manager? I'm using CurseBreaker -  https://github.com/AcidWeb/CurseBreaker - a small CLI addon manager which can install/update from various addon sites like curse and wowinterface as well as update weakaura from wago.io

I'll test the fixes later today and let you know if anything is not working as intended :-)

**Comment by liquidbase** [comment] 2020-10-24 10:51
Nice. AddOn-Updater in Python, perfectly for Linux :D

I will continue to test what causes the error with the TimeTracker.

**Comment by HolySephi** [comment] 2020-10-24 15:01
Runes are working again in connect with unitframe mode - thank you very much :-)
I think you can release this fix as version on curseforge etc
I'll watch out for the timer bar problem - if it emerges again with the current git version i'll reply to this ticket or if you want to close it i could reopen it/open a new one.

**Comment by liquidbase** [comment] 2020-10-24 18:15
> if it emerges again with the current git version i'll reply to this ticket or if you want to close it i could reopen it/open a new one.
I leave the ticket open as a question. Then it makes it easier in direct reference, if necessary, to roll up the whole thing again.

But I'm happy that the problem with the runes has been solved and that the TimerBar no longer appears :)

**Closed** 2020-12-07 04:25 UTC
Labels: question
